name: Preview

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install
        run: |
          pnpm install

      - name: Build
        run: |
          pnpm run build

      - name: Deploy preview
        id: deploy-preview
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_KEY }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: version upload --message "Deployed by GitHub Actions branch ${{ github.ref }}"

      - name: Create comment file
        run: |
          cat  << EOF > comment.md
          ## Preview
          <table>
            <tr>
              <td>Preview URL</td>
              <td>https://preview.${{ github.repository }}.com</td>
            </tr>
          </table>
          EOF

      - name: Create PR comment
        if: ${{ steps.deploy-preview.outcome == 'success' }}
        run: |
          gh pr comment ${{ github.event.number }} --body-file comment.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
