name: Preview

on:
  pull_request:
    types: [ opened, synchronize ]

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Install
        run: pnpm install
      - name: Build pages
        run: pnpm run pages:build
      - name: Build storybook
        run: pnpm run storybook:build
      - name: Deploy pages preview
        id: deploy-pages-preview
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_KEY }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: versions upload --message "Deployed pages by GitHub Actions branch ${{ github.ref_name }}"
      - name: Deploy storybook preview
        id: deploy-storybook-preview
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_KEY }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy ./storybook-static --project-name "color-palette-storybook" --branch="${{ github.ref_name }}"
      - name: Create comment file
        run: |
          cat  << EOF > comment.md
          ## 🚀 Deploying color-palette with Cloudflare Pages and Cloudflare Storybook
          <table>
            <tr>
              <th scope="row">Preview URL</th>
              <td>${{ steps.deploy-pages-preview.outputs.deployment-url }}</td>
            </tr>
            <tr>
              <th scope="row">Storybook Preview URL</th>
              <td>${{ steps.deploy-storybook-preview.outputs.deployment-url }}</td>
            </tr>
            <tr>
              <th scope="row">Storybook branch URL</th>
              <td>${{ steps.deploy-storybook-preview.outputs.deployment-url }}</td>
            </tr>
          </table>
          EOF
      - name: Create PR comment
        if: ${{ steps.deploy-pages-preview.outcome == 'success' && steps.deploy-storybook-preview.outcome == 'success' }}
        run: gh pr comment ${{ github.event.number }} --body-file comment.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
