name: Preview

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install
        run: |
          pnpm install

      - name: Build 
        strategy:
          matrix:
            target: ['pages', 'storybook']
        steps:
          - name: Build ${{ matrix.target }}
            run: |
              pnpm run ${{ matrix.target }}:build 

      - name: Deploy pages preview
        id: deploy-pages-preview
        uses: cloudflare/wrangler-action@v3
          with:
            apiToken: ${{ secrets.CF_API_KEY }}
            accountId: ${{ secrets.CF_ACCOUNT_ID }}
            command: versions upload --message "Deployed pages by GitHub Actions branch ${{ github.ref }}"

      - name: Deploy storybook preview
        id: deploy-storybook-preview
        uses: cloudflare/wrangler-action@v3
          with:
            apiToken: ${{ secrets.CF_API_KEY }}
            accountId: ${{ secrets.CF_ACCOUNT_ID }}
            command: versions upload --message "Deployed storybook by GitHub Actions branch ${{ github.ref }}"

      - name: Create comment file
        run: |
          cat  << EOF > comment.md
          ## Preview
          <table>
            <tr>
              <td>Preview URL</td>
              <td>${{ steps.deploy-pages-preview.outputs.url }}</td>
              <td>${{ steps.deploy-storybook-preview.outputs.url }}</td>
            </tr>
          </table>
          EOF

      - name: Create PR comment
        if: ${{ steps.deploy-pages-preview.outcome == 'success' && steps.deploy-storybook-preview.outcome == 'success' }}
        run: |
          gh pr comment ${{ github.event.number }} --body-file comment.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
